- name: Caonfiguring cart
  hosts: cart
  become: yes
  tasks:
  - name: setting up npm source
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: check if roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: create roboshop user
    when: output.rc == 1
    ansible.builtin.user:
     name: roboshop
  
  - name: check if app directory exists or not
    ansible.builtin.stat:
      path: /app
    register: out

  - name: create app directory if it doest not exist
    when: out.stat.exists == false
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download cart artifact
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/cart.zip
     path: /tmp

  - name: Extract cart
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
     chdir: /app

  - name: Copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: Demon relod
    ansible.builtin.systemd:
      daemon-reload: true

  - name: enable and start cart service
    ansible.builtin.service:
       name: cart
       enabled: yes
       state: started

















       

