- name: Configure Dispatch
  hosts: dispatch
  become: yes
  tasks:
  - name: Install golang
    ansible.builtin.yum:
      name: golang
      state: installed

  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  - name: create roboshop user
    when: out.rc == 1
    ansible.builtin.user:
      name: roboshop

  - name: check if directory exist or not
    ansible.builtin.stat:
      path: /app
    register: output    

  - name: create directory
    when: output.stat.exists == false
    ansible.builtin.file:
      parth: /app
      state: directory

  - name: download and extract dispatch
    ansibl.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /app
      remote_src: yes

  - name: download dependencies
    ansible.builtin.command: "{{item}}"
    args:
      chdir: /app
    loop: 
    - go mod init dispatch
    - go get 
    - go build
  
  - name: copy service
    ansible.builtin.copy:
      src: dispatch.service 
      dest: /etc/systemd/system/dispatch.service

  - name: deamon reload
    ansible.builtin.systemd:
      daemon-reload: true

  - name: enable and start dispatch
    ansible.builtin.service:
      name: dispatch
      enabled: true
      state: started


  
