- name: Configuring mysql
  hosts: mysql
  become: yes
  tasks: 
  - name: disable mysql
    ansible.builtin.command: yum module disable mysql -y 

  - name: copy mysql repo
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install mysql
    ansible.builtin.yum:
      name: mysql-community-server
      state: installed
  
  - name: restart and enable
    ansible.builtin.service:
      name: mysqld
      enabled: true
      state: started

  - name: change default password
    ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1