- name: Caonfiguring user
  hosts: user
  become: yes
  tasks:
  - name: setting up npm source
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: check if roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: create roboshop user
    when: output.rc == 1
    ansible.builtin.user:
     name: roboshop
  
  - name: check if app directory exists or not
    ansible.builtin.stat:
      path: /app
    register: out

  - name: create app directory if it doest not exist
    when: out.stat.exists == false
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catlogue artifact
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/user.zip
     path: /tmp

  - name: Extract user
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copy user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: Demon relod
    ansible.builtin.systemd:
      daemon-reload: true
  
  - name: enable and start user service
    ansible.builtin.service:
       name: user
       enabled: yes
       state: started
  

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongo org shell
    ansible.builtin.yum: 
     name: mongodb-org-shell
     state: installed

  - name: load data
    ansible.builtin.shell: mongo --host mongodb.preprv.online </app/schema/user.js

  - name: enable and start user service
    ansible.builtin.service:
       name: user
       state: restarted

















       

